// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace MeesSDK
{
	[Table("building_set_ids")]
	public class BuildingSetId
	{
		[Column("id"             , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int Id             { get; set; } // integer
		[Column("building_set_id"                                                                                  )] public int BuildingSetId1 { get; set; } // integer
		[Column("building_id"                                                                                      )] public int BuildingId     { get; set; } // integer

		#region Associations
		/// <summary>
		/// fk_building_set_id
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(BuildingSetId1), OtherKey = nameof(MeesSDK.BuildingSet.Id))]
		public BuildingSet BuildingSet { get; set; } = null!;
		#endregion
	}
}
