// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace MeesSDK
{
	[Table("__building_types")]
	public class BuildingType
	{
		[Column("id"              )] public int?     Id             { get; set; } // integer
		[Column("depc_id"         )] public int?     DepcId         { get; set; } // integer
		[Column("area"            )] public decimal? Area           { get; set; } // numeric(16,4)
		[Column("property_type_id")] public int?     PropertyTypeId { get; set; } // integer
		[Column("built_form_id"   )] public int?     BuiltFormId    { get; set; } // integer
	}
}
