// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace MeesSDK
{
	[Table("constituencies")]
	public class Constituency
	{
		[Column("id"  , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int     Id   { get; set; } // integer
		[Column("code"                                                                                  )] public string? Code { get; set; } // character varying(128)
		[Column("name"                                                                                  )] public string? Name { get; set; } // character varying(256)

		#region Associations
		/// <summary>
		/// fk_constituency_populations_constituency_id backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(ConstituencyPopulation.ConstituencyId))]
		public IEnumerable<ConstituencyPopulation> ConstituencyPopulations { get; set; } = null!;

		/// <summary>
		/// fk_postcode_constituency_id backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Postcode.ConstituencyId))]
		public IEnumerable<Postcode> Postcodes { get; set; } = null!;
		#endregion
	}
}
