// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace MeesSDK
{
	[Table("constituency_populations")]
	public class ConstituencyPopulation
	{
		[Column("id"             )] public int?   Id             { get; set; } // integer
		[Column("year"           )] public short? Year           { get; set; } // smallint
		[Column("total"          )] public int?   Total          { get; set; } // integer
		[Column("men"            )] public int?   Men            { get; set; } // integer
		[Column("women"          )] public int?   Women          { get; set; } // integer
		[Column("women_0"        )] public int?   Women0         { get; set; } // integer
		[Column("women_1"        )] public int?   Women1         { get; set; } // integer
		[Column("women_2"        )] public int?   Women2         { get; set; } // integer
		[Column("women_3"        )] public int?   Women3         { get; set; } // integer
		[Column("women_4"        )] public int?   Women4         { get; set; } // integer
		[Column("women_5"        )] public int?   Women5         { get; set; } // integer
		[Column("women_6"        )] public int?   Women6         { get; set; } // integer
		[Column("women_7"        )] public int?   Women7         { get; set; } // integer
		[Column("women_8"        )] public int?   Women8         { get; set; } // integer
		[Column("women_9"        )] public int?   Women9         { get; set; } // integer
		[Column("women_10"       )] public int?   Women10        { get; set; } // integer
		[Column("women_11"       )] public int?   Women11        { get; set; } // integer
		[Column("women_12"       )] public int?   Women12        { get; set; } // integer
		[Column("women_13"       )] public int?   Women13        { get; set; } // integer
		[Column("women_14"       )] public int?   Women14        { get; set; } // integer
		[Column("women_15"       )] public int?   Women15        { get; set; } // integer
		[Column("women_16"       )] public int?   Women16        { get; set; } // integer
		[Column("women_17"       )] public int?   Women17        { get; set; } // integer
		[Column("women_18"       )] public int?   Women18        { get; set; } // integer
		[Column("women_19"       )] public int?   Women19        { get; set; } // integer
		[Column("women_20"       )] public int?   Women20        { get; set; } // integer
		[Column("women_21"       )] public int?   Women21        { get; set; } // integer
		[Column("women_22"       )] public int?   Women22        { get; set; } // integer
		[Column("women_23"       )] public int?   Women23        { get; set; } // integer
		[Column("women_24"       )] public int?   Women24        { get; set; } // integer
		[Column("women_25"       )] public int?   Women25        { get; set; } // integer
		[Column("women_26"       )] public int?   Women26        { get; set; } // integer
		[Column("women_27"       )] public int?   Women27        { get; set; } // integer
		[Column("women_28"       )] public int?   Women28        { get; set; } // integer
		[Column("women_29"       )] public int?   Women29        { get; set; } // integer
		[Column("women_30"       )] public int?   Women30        { get; set; } // integer
		[Column("women_31"       )] public int?   Women31        { get; set; } // integer
		[Column("women_32"       )] public int?   Women32        { get; set; } // integer
		[Column("women_33"       )] public int?   Women33        { get; set; } // integer
		[Column("women_34"       )] public int?   Women34        { get; set; } // integer
		[Column("women_35"       )] public int?   Women35        { get; set; } // integer
		[Column("women_36"       )] public int?   Women36        { get; set; } // integer
		[Column("women_37"       )] public int?   Women37        { get; set; } // integer
		[Column("women_38"       )] public int?   Women38        { get; set; } // integer
		[Column("women_39"       )] public int?   Women39        { get; set; } // integer
		[Column("women_40"       )] public int?   Women40        { get; set; } // integer
		[Column("women_41"       )] public int?   Women41        { get; set; } // integer
		[Column("women_42"       )] public int?   Women42        { get; set; } // integer
		[Column("women_43"       )] public int?   Women43        { get; set; } // integer
		[Column("women_44"       )] public int?   Women44        { get; set; } // integer
		[Column("women_45"       )] public int?   Women45        { get; set; } // integer
		[Column("women_46"       )] public int?   Women46        { get; set; } // integer
		[Column("women_47"       )] public int?   Women47        { get; set; } // integer
		[Column("women_48"       )] public int?   Women48        { get; set; } // integer
		[Column("women_49"       )] public int?   Women49        { get; set; } // integer
		[Column("women_50"       )] public int?   Women50        { get; set; } // integer
		[Column("women_51"       )] public int?   Women51        { get; set; } // integer
		[Column("women_52"       )] public int?   Women52        { get; set; } // integer
		[Column("women_53"       )] public int?   Women53        { get; set; } // integer
		[Column("women_54"       )] public int?   Women54        { get; set; } // integer
		[Column("women_55"       )] public int?   Women55        { get; set; } // integer
		[Column("women_56"       )] public int?   Women56        { get; set; } // integer
		[Column("women_57"       )] public int?   Women57        { get; set; } // integer
		[Column("women_58"       )] public int?   Women58        { get; set; } // integer
		[Column("women_59"       )] public int?   Women59        { get; set; } // integer
		[Column("women_60"       )] public int?   Women60        { get; set; } // integer
		[Column("women_61"       )] public int?   Women61        { get; set; } // integer
		[Column("women_62"       )] public int?   Women62        { get; set; } // integer
		[Column("women_63"       )] public int?   Women63        { get; set; } // integer
		[Column("women_64"       )] public int?   Women64        { get; set; } // integer
		[Column("women_65"       )] public int?   Women65        { get; set; } // integer
		[Column("women_66"       )] public int?   Women66        { get; set; } // integer
		[Column("women_67"       )] public int?   Women67        { get; set; } // integer
		[Column("women_68"       )] public int?   Women68        { get; set; } // integer
		[Column("women_69"       )] public int?   Women69        { get; set; } // integer
		[Column("women_70"       )] public int?   Women70        { get; set; } // integer
		[Column("women_71"       )] public int?   Women71        { get; set; } // integer
		[Column("women_72"       )] public int?   Women72        { get; set; } // integer
		[Column("women_73"       )] public int?   Women73        { get; set; } // integer
		[Column("women_74"       )] public int?   Women74        { get; set; } // integer
		[Column("women_75"       )] public int?   Women75        { get; set; } // integer
		[Column("women_76"       )] public int?   Women76        { get; set; } // integer
		[Column("women_77"       )] public int?   Women77        { get; set; } // integer
		[Column("women_78"       )] public int?   Women78        { get; set; } // integer
		[Column("women_79"       )] public int?   Women79        { get; set; } // integer
		[Column("women_80"       )] public int?   Women80        { get; set; } // integer
		[Column("women_81"       )] public int?   Women81        { get; set; } // integer
		[Column("women_82"       )] public int?   Women82        { get; set; } // integer
		[Column("women_83"       )] public int?   Women83        { get; set; } // integer
		[Column("women_84"       )] public int?   Women84        { get; set; } // integer
		[Column("women_85"       )] public int?   Women85        { get; set; } // integer
		[Column("women_86"       )] public int?   Women86        { get; set; } // integer
		[Column("women_87"       )] public int?   Women87        { get; set; } // integer
		[Column("women_88"       )] public int?   Women88        { get; set; } // integer
		[Column("women_89"       )] public int?   Women89        { get; set; } // integer
		[Column("women_90"       )] public int?   Women90        { get; set; } // integer
		[Column("men_0"          )] public int?   Men0           { get; set; } // integer
		[Column("men_1"          )] public int?   Men1           { get; set; } // integer
		[Column("men_2"          )] public int?   Men2           { get; set; } // integer
		[Column("men_3"          )] public int?   Men3           { get; set; } // integer
		[Column("men_4"          )] public int?   Men4           { get; set; } // integer
		[Column("men_5"          )] public int?   Men5           { get; set; } // integer
		[Column("men_6"          )] public int?   Men6           { get; set; } // integer
		[Column("men_7"          )] public int?   Men7           { get; set; } // integer
		[Column("men_8"          )] public int?   Men8           { get; set; } // integer
		[Column("men_9"          )] public int?   Men9           { get; set; } // integer
		[Column("men_10"         )] public int?   Men10          { get; set; } // integer
		[Column("men_11"         )] public int?   Men11          { get; set; } // integer
		[Column("men_12"         )] public int?   Men12          { get; set; } // integer
		[Column("men_13"         )] public int?   Men13          { get; set; } // integer
		[Column("men_14"         )] public int?   Men14          { get; set; } // integer
		[Column("men_15"         )] public int?   Men15          { get; set; } // integer
		[Column("men_16"         )] public int?   Men16          { get; set; } // integer
		[Column("men_17"         )] public int?   Men17          { get; set; } // integer
		[Column("men_18"         )] public int?   Men18          { get; set; } // integer
		[Column("men_19"         )] public int?   Men19          { get; set; } // integer
		[Column("men_20"         )] public int?   Men20          { get; set; } // integer
		[Column("men_21"         )] public int?   Men21          { get; set; } // integer
		[Column("men_22"         )] public int?   Men22          { get; set; } // integer
		[Column("men_23"         )] public int?   Men23          { get; set; } // integer
		[Column("men_24"         )] public int?   Men24          { get; set; } // integer
		[Column("men_25"         )] public int?   Men25          { get; set; } // integer
		[Column("men_26"         )] public int?   Men26          { get; set; } // integer
		[Column("men_27"         )] public int?   Men27          { get; set; } // integer
		[Column("men_28"         )] public int?   Men28          { get; set; } // integer
		[Column("men_29"         )] public int?   Men29          { get; set; } // integer
		[Column("men_30"         )] public int?   Men30          { get; set; } // integer
		[Column("men_31"         )] public int?   Men31          { get; set; } // integer
		[Column("men_32"         )] public int?   Men32          { get; set; } // integer
		[Column("men_33"         )] public int?   Men33          { get; set; } // integer
		[Column("men_34"         )] public int?   Men34          { get; set; } // integer
		[Column("men_35"         )] public int?   Men35          { get; set; } // integer
		[Column("men_36"         )] public int?   Men36          { get; set; } // integer
		[Column("men_37"         )] public int?   Men37          { get; set; } // integer
		[Column("men_38"         )] public int?   Men38          { get; set; } // integer
		[Column("men_39"         )] public int?   Men39          { get; set; } // integer
		[Column("men_40"         )] public int?   Men40          { get; set; } // integer
		[Column("men_41"         )] public int?   Men41          { get; set; } // integer
		[Column("men_42"         )] public int?   Men42          { get; set; } // integer
		[Column("men_43"         )] public int?   Men43          { get; set; } // integer
		[Column("men_44"         )] public int?   Men44          { get; set; } // integer
		[Column("men_45"         )] public int?   Men45          { get; set; } // integer
		[Column("men_46"         )] public int?   Men46          { get; set; } // integer
		[Column("men_47"         )] public int?   Men47          { get; set; } // integer
		[Column("men_48"         )] public int?   Men48          { get; set; } // integer
		[Column("men_49"         )] public int?   Men49          { get; set; } // integer
		[Column("men_50"         )] public int?   Men50          { get; set; } // integer
		[Column("men_51"         )] public int?   Men51          { get; set; } // integer
		[Column("men_52"         )] public int?   Men52          { get; set; } // integer
		[Column("men_53"         )] public int?   Men53          { get; set; } // integer
		[Column("men_54"         )] public int?   Men54          { get; set; } // integer
		[Column("men_55"         )] public int?   Men55          { get; set; } // integer
		[Column("men_56"         )] public int?   Men56          { get; set; } // integer
		[Column("men_57"         )] public int?   Men57          { get; set; } // integer
		[Column("men_58"         )] public int?   Men58          { get; set; } // integer
		[Column("men_59"         )] public int?   Men59          { get; set; } // integer
		[Column("men_60"         )] public int?   Men60          { get; set; } // integer
		[Column("men_61"         )] public int?   Men61          { get; set; } // integer
		[Column("men_62"         )] public int?   Men62          { get; set; } // integer
		[Column("men_63"         )] public int?   Men63          { get; set; } // integer
		[Column("men_64"         )] public int?   Men64          { get; set; } // integer
		[Column("men_65"         )] public int?   Men65          { get; set; } // integer
		[Column("men_66"         )] public int?   Men66          { get; set; } // integer
		[Column("men_67"         )] public int?   Men67          { get; set; } // integer
		[Column("men_68"         )] public int?   Men68          { get; set; } // integer
		[Column("men_69"         )] public int?   Men69          { get; set; } // integer
		[Column("men_70"         )] public int?   Men70          { get; set; } // integer
		[Column("men_71"         )] public int?   Men71          { get; set; } // integer
		[Column("men_72"         )] public int?   Men72          { get; set; } // integer
		[Column("men_73"         )] public int?   Men73          { get; set; } // integer
		[Column("men_74"         )] public int?   Men74          { get; set; } // integer
		[Column("men_75"         )] public int?   Men75          { get; set; } // integer
		[Column("men_76"         )] public int?   Men76          { get; set; } // integer
		[Column("men_77"         )] public int?   Men77          { get; set; } // integer
		[Column("men_78"         )] public int?   Men78          { get; set; } // integer
		[Column("men_79"         )] public int?   Men79          { get; set; } // integer
		[Column("men_80"         )] public int?   Men80          { get; set; } // integer
		[Column("men_81"         )] public int?   Men81          { get; set; } // integer
		[Column("men_82"         )] public int?   Men82          { get; set; } // integer
		[Column("men_83"         )] public int?   Men83          { get; set; } // integer
		[Column("men_84"         )] public int?   Men84          { get; set; } // integer
		[Column("men_85"         )] public int?   Men85          { get; set; } // integer
		[Column("men_86"         )] public int?   Men86          { get; set; } // integer
		[Column("men_87"         )] public int?   Men87          { get; set; } // integer
		[Column("men_88"         )] public int?   Men88          { get; set; } // integer
		[Column("men_89"         )] public int?   Men89          { get; set; } // integer
		[Column("men_90"         )] public int?   Men90          { get; set; } // integer
		[Column("constituency_id")] public int?   ConstituencyId { get; set; } // integer

		#region Associations
		/// <summary>
		/// fk_constituency_populations_constituency_id
		/// </summary>
		[Association(ThisKey = nameof(ConstituencyId), OtherKey = nameof(MeesSDK.Constituency.Id))]
		public Constituency? Constituency { get; set; }
		#endregion
	}
}
