// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace MeesSDK
{
	[Table("deprivation_index_column_labels")]
	public class DeprivationIndexColumnLabel
	{
		[Column("id"         , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int     Id          { get; set; } // integer
		[Column("code"                                                                                         )] public string? Code        { get; set; } // character varying(512)
		[Column("description"                                                                                  )] public string? Description { get; set; } // character varying(512)
	}
}
