// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace MeesSDK
{
	[Table("epcs")]
	public class Epc
	{
		[Column("id"                        , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id                       { get; set; } // integer
		[Column("lmk_key"                   , CanBeNull    = false                                                             )] public string    LmkKey                   { get; set; } = null!; // character varying(256)
		[Column("asset_rating"                                                                                                 )] public int?      AssetRating              { get; set; } // integer
		[Column("current_energy_rating"                                                                                        )] public string?   CurrentEnergyRating      { get; set; } // character varying(56)
		[Column("inspection_date"                                                                                              )] public DateTime? InspectionDate           { get; set; } // date
		[Column("new_build_benchmark"                                                                                          )] public int?      NewBuildBenchmark        { get; set; } // integer
		[Column("existing_stock_benchmark"                                                                                     )] public int?      ExistingStockBenchmark   { get; set; } // integer
		[Column("building_level"                                                                                               )] public int?      BuildingLevel            { get; set; } // integer
		[Column("floor_area"                                                                                                   )] public int?      FloorArea                { get; set; } // integer
		[Column("standard_emissions"                                                                                           )] public decimal?  StandardEmissions        { get; set; } // numeric(10,4)
		[Column("target_emissions"                                                                                             )] public decimal?  TargetEmissions          { get; set; } // numeric(10,4)
		[Column("typical_emissions"                                                                                            )] public decimal?  TypicalEmissions         { get; set; } // numeric(10,4)
		[Column("actual_emissions"                                                                                             )] public decimal?  ActualEmissions          { get; set; } // numeric(10,4)
		[Column("aircon_present"                                                                                               )] public bool?     AirconPresent            { get; set; } // boolean
		[Column("aircon_kw_rating"                                                                                             )] public decimal?  AirconKwRating           { get; set; } // numeric(8,1)
		[Column("estimated_aircon_kw_rating"                                                                                   )] public decimal?  EstimatedAirconKwRating  { get; set; } // numeric(8,1)
		[Column("ac_inspection_commissioned"                                                                                   )] public char?     AcInspectionCommissioned { get; set; } // character(1)
		[Column("primary_energy_value"                                                                                         )] public decimal?  PrimaryEnergyValue       { get; set; } // numeric(10,4)
		[Column("uprn"                                                                                                         )] public string?   Uprn                     { get; set; } // character varying(32)
		[Column("uprn_source"                                                                                                  )] public string?   UprnSource               { get; set; } // character varying(32)
		[Column("epc_r2"                                                                                                       )] public int       EpcR2                    { get; set; } // integer
		[Column("epc_r3"                                                                                                       )] public int       EpcR3                    { get; set; } // integer
		[Column("epc_r4"                                                                                                       )] public int       EpcR4                    { get; set; } // integer
		[Column("epc_w1"                                                                                                       )] public int       EpcW1                    { get; set; } // integer
		[Column("epc_w2"                                                                                                       )] public int       EpcW2                    { get; set; } // integer
		[Column("epc_r5"                                                                                                       )] public int       EpcR5                    { get; set; } // integer
		[Column("epc_l7"                                                                                                       )] public int       EpcL7                    { get; set; } // integer
		[Column("epc_r1"                                                                                                       )] public int       EpcR1                    { get; set; } // integer
		[Column("epc_h4"                                                                                                       )] public int       EpcH4                    { get; set; } // integer
		[Column("epc_e8"                                                                                                       )] public int       EpcE8                    { get; set; } // integer
		[Column("epc_e7"                                                                                                       )] public int       EpcE7                    { get; set; } // integer
		[Column("epc_e5"                                                                                                       )] public int       EpcE5                    { get; set; } // integer
		[Column("epc_c1"                                                                                                       )] public int       EpcC1                    { get; set; } // integer
		[Column("epc_e4"                                                                                                       )] public int       EpcE4                    { get; set; } // integer
		[Column("epc_l5"                                                                                                       )] public int       EpcL5                    { get; set; } // integer
		[Column("epc_h8"                                                                                                       )] public int       EpcH8                    { get; set; } // integer
		[Column("epc_v1"                                                                                                       )] public int       EpcV1                    { get; set; } // integer
		[Column("epc_h7"                                                                                                       )] public int       EpcH7                    { get; set; } // integer
		[Column("epc_e2"                                                                                                       )] public int       EpcE2                    { get; set; } // integer
		[Column("epc_f5"                                                                                                       )] public int       EpcF5                    { get; set; } // integer
		[Column("epc_h3"                                                                                                       )] public int       EpcH3                    { get; set; } // integer
		[Column("epc_h1"                                                                                                       )] public int       EpcH1                    { get; set; } // integer
		[Column("epc_h6"                                                                                                       )] public int       EpcH6                    { get; set; } // integer
		[Column("epc_l2"                                                                                                       )] public int       EpcL2                    { get; set; } // integer
		[Column("epc_c3"                                                                                                       )] public int       EpcC3                    { get; set; } // integer
		[Column("epc_l1"                                                                                                       )] public int       EpcL1                    { get; set; } // integer
		[Column("epc_w3"                                                                                                       )] public int       EpcW3                    { get; set; } // integer
		[Column("epc_h5"                                                                                                       )] public int       EpcH5                    { get; set; } // integer
		[Column("epc_e6"                                                                                                       )] public int       EpcE6                    { get; set; } // integer
		[Column("epc_h2"                                                                                                       )] public int       EpcH2                    { get; set; } // integer
		[Column("epc_l3"                                                                                                       )] public int       EpcL3                    { get; set; } // integer
		[Column("epc_l6"                                                                                                       )] public int       EpcL6                    { get; set; } // integer
		[Column("epc_e3"                                                                                                       )] public int       EpcE3                    { get; set; } // integer
		[Column("epc_l4"                                                                                                       )] public int       EpcL4                    { get; set; } // integer
		[Column("epc_w4"                                                                                                       )] public int       EpcW4                    { get; set; } // integer
		[Column("epc_e1"                                                                                                       )] public int       EpcE1                    { get; set; } // integer
		[Column("epc_c2"                                                                                                       )] public int       EpcC2                    { get; set; } // integer
		[Column("epc_f4"                                                                                                       )] public int       EpcF4                    { get; set; } // integer
		[Column("epc_f1"                                                                                                       )] public int       EpcF1                    { get; set; } // integer
		[Column("epc_f2"                                                                                                       )] public int       EpcF2                    { get; set; } // integer
		[Column("epc_f3"                                                                                                       )] public int       EpcF3                    { get; set; } // integer
		[Column("epc_f6"                                                                                                       )] public int       EpcF6                    { get; set; } // integer
		[Column("lodgement_date"                                                                                               )] public DateTime? LodgementDate            { get; set; } // date
		[Column("building_id"                                                                                                  )] public int?      BuildingId               { get; set; } // integer
		[Column("main_heating_fuel_id"                                                                                         )] public int?      MainHeatingFuelId        { get; set; } // integer
		[Column("epc_transaction_type_id"                                                                                      )] public int?      EpcTransactionTypeId     { get; set; } // integer
		[Column("ncm_property_type_id"                                                                                         )] public int?      NcmPropertyTypeId        { get; set; } // integer
		[Column("indoor_environment_type_id"                                                                                   )] public int?      IndoorEnvironmentTypeId  { get; set; } // integer
		[Column("uprn_source_id"                                                                                               )] public int?      UprnSourceId             { get; set; } // integer

		#region Associations
		/// <summary>
		/// epcs_ncm_property_type_id_fkey
		/// </summary>
		[Association(ThisKey = nameof(NcmPropertyTypeId), OtherKey = nameof(MeesSDK.NcmPropertyType.Id))]
		public NcmPropertyType? NcmPropertyType { get; set; }

		/// <summary>
		/// fk_building_environment_id
		/// </summary>
		[Association(ThisKey = nameof(IndoorEnvironmentTypeId), OtherKey = nameof(MeesSDK.IndoorEnvironmentType.Id))]
		public IndoorEnvironmentType? IndoorEnvironmentType { get; set; }

		/// <summary>
		/// fk_epc_building_id
		/// </summary>
		[Association(ThisKey = nameof(BuildingId), OtherKey = nameof(MeesSDK.Building.Id))]
		public Building? Building { get; set; }

		/// <summary>
		/// fk_epc_transaction_type_id
		/// </summary>
		[Association(ThisKey = nameof(EpcTransactionTypeId), OtherKey = nameof(MeesSDK.EpcTransactionType.Id))]
		public EpcTransactionType? EpcTransactionType { get; set; }

		/// <summary>
		/// fk_main_heating_fuel_id
		/// </summary>
		[Association(ThisKey = nameof(MainHeatingFuelId), OtherKey = nameof(MeesSDK.MainHeatingFuel.Id))]
		public MainHeatingFuel? MainHeatingFuel { get; set; }

		/// <summary>
		/// fk_uprn_source_id
		/// </summary>
		[Association(ThisKey = nameof(UprnSourceId), OtherKey = nameof(MeesSDK.UprnSource.Id))]
		public UprnSource? UprnSource1 { get; set; }
		#endregion
	}
}
