// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace MeesSDK
{
	[Table("epc_ratings")]
	public class EpcRating
	{
		[Column("id"         , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int      Id         { get; set; } // integer
		[Column("rating"                                                                  )] public string?  Rating     { get; set; } // character varying(3)
		[Column("lower_bound"                                                             )] public decimal? LowerBound { get; set; } // numeric(8,4)
		[Column("upper_bound"                                                             )] public decimal? UpperBound { get; set; } // numeric(9,4)
		[Column("epc_type"                                                                )] public string?  EpcType    { get; set; } // character varying(56)
	}
}
