// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace MeesSDK
{
	[Table("glazed_area_sizes")]
	public class GlazedAreaSize
	{
		[Column("id"  , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int     Id   { get; set; } // integer
		[Column("name"                                                                                  )] public string? Name { get; set; } // character varying(56)

		#region Associations
		/// <summary>
		/// depcs_glazed_area_size_id_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Depc.GlazedAreaSizeId))]
		public IEnumerable<Depc> Depcs { get; set; } = null!;
		#endregion
	}
}
