// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace MeesSDK
{
	[Table("indoor_environment_types")]
	public class IndoorEnvironmentType
	{
		[Column("id"  , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int    Id   { get; set; } // integer
		[Column("name", CanBeNull    = false                                                             )] public string Name { get; set; } = null!; // character varying(256)

		#region Associations
		/// <summary>
		/// fk_building_environment_id backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Epc.IndoorEnvironmentTypeId))]
		public IEnumerable<Epc> Epcs { get; set; } = null!;
		#endregion
	}
}
