// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace MeesSDK
{
	[Table("local_authority_deprivation_indices")]
	public class LocalAuthorityDeprivationIndex
	{
		[Column("id"                                                        , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int      Id                                             { get; set; } // integer
		[Column("Avg Score-a. IMD"                                                                                                                            )] public decimal? AvgScoreAImd                                   { get; set; } // numeric(8,2)
		[Column("Local concentration-a. IMD"                                                                                                                  )] public decimal? LocalConcentrationAImd                         { get; set; } // numeric(8,2)
		[Column("Rank local concentration-a. IMD"                                                                                                             )] public decimal? RankLocalConcentrationAImd                     { get; set; } // numeric(8,2)
		[Column("Rank Avg rank-a. IMD"                                                                                                                        )] public decimal? RankAvgRankAImd                                { get; set; } // numeric(8,2)
		[Column("Rank extent-a. IMD"                                                                                                                          )] public decimal? RankExtentAImd                                 { get; set; } // numeric(8,2)
		[Column("Rank prop LSOAs worst 10% nat-a. IMD"                                                                                                        )] public decimal? RankPropLsoAsWorst10NatAImd                    { get; set; } // numeric(8,2)
		[Column("Extent-a. IMD"                                                                                                                               )] public decimal? ExtentAImd                                     { get; set; } // numeric(8,2)
		[Column("prop LSOA worst 10% nat-a. IMD"                                                                                                              )] public decimal? PropLsoaWorst10NatAImd                         { get; set; } // numeric(8,2)
		[Column("Avg Rank-a. IMD"                                                                                                                             )] public decimal? AvgRankAImd                                    { get; set; } // numeric(8,2)
		[Column("Rank Avg score-a. IMD"                                                                                                                       )] public decimal? RankAvgScoreAImd                               { get; set; } // numeric(8,2)
		[Column("Rank Avg rank-b. Money-dep"                                                                                                                  )] public decimal? RankAvgRankBMoneyDep                           { get; set; } // numeric(8,2)
		[Column("Rank scale-b. Money-dep"                                                                                                                     )] public decimal? RankScaleBMoneyDep                             { get; set; } // numeric(8,2)
		[Column("prop LSOA worst 10% nat-b. Money-dep"                                                                                                        )] public decimal? PropLsoaWorst10NatBMoneyDep                    { get; set; } // numeric(8,2)
		[Column("Avg Rank-b. Money-dep"                                                                                                                       )] public decimal? AvgRankBMoneyDep                               { get; set; } // numeric(8,2)
		[Column("Rank Avg score-b. Money-dep"                                                                                                                 )] public decimal? RankAvgScoreBMoneyDep                          { get; set; } // numeric(8,2)
		[Column("Rank prop LSOAs worst 10% nat-b. Money-dep"                                                                                                  )] public decimal? RankPropLsoAsWorst10NatBMoneyDep               { get; set; } // numeric(8,2)
		[Column("Scale-b. Money-dep"                                                                                                                          )] public decimal? ScaleBMoneyDep                                 { get; set; } // numeric(8,2)
		[Column("Avg Score-b. Money-dep"                                                                                                                      )] public decimal? AvgScoreBMoneyDep                              { get; set; } // numeric(8,2)
		[Column("Rank prop LSOAs worst 10% nat-c. Employment-dep"                                                                                             )] public decimal? RankPropLsoAsWorst10NatCEmploymentDep          { get; set; } // numeric(8,2)
		[Column("Rank scale-c. Employment-dep"                                                                                                                )] public decimal? RankScaleCEmploymentDep                        { get; set; } // numeric(8,2)
		[Column("Rank Avg score-c. Employment-dep"                                                                                                            )] public decimal? RankAvgScoreCEmploymentDep                     { get; set; } // numeric(8,2)
		[Column("Scale-c. Employment-dep"                                                                                                                     )] public decimal? ScaleCEmploymentDep                            { get; set; } // numeric(8,2)
		[Column("Rank Avg rank-c. Employment-dep"                                                                                                             )] public decimal? RankAvgRankCEmploymentDep                      { get; set; } // numeric(8,2)
		[Column("Avg Rank-c. Employment-dep"                                                                                                                  )] public decimal? AvgRankCEmploymentDep                          { get; set; } // numeric(8,2)
		[Column("prop LSOA worst 10% nat-c. Employment-dep"                                                                                                   )] public decimal? PropLsoaWorst10NatCEmploymentDep               { get; set; } // numeric(8,2)
		[Column("Avg Score-c. Employment-dep"                                                                                                                 )] public decimal? AvgScoreCEmploymentDep                         { get; set; } // numeric(8,2)
		[Column("Rank Avg rank-d. Ed, Skill, Train"                                                                                                           )] public decimal? RankAvgRankDEdSkillTrain                       { get; set; } // numeric(8,2)
		[Column("Rank Avg score-d. Ed, Skill, Train"                                                                                                          )] public decimal? RankAvgScoreDEdSkillTrain                      { get; set; } // numeric(8,2)
		[Column("Avg Rank-d. Ed, Skill, Train"                                                                                                                )] public decimal? AvgRankDEdSkillTrain                           { get; set; } // numeric(8,2)
		[Column("Avg Score-d. Ed, Skill, Train"                                                                                                               )] public decimal? AvgScoreDEdSkillTrain                          { get; set; } // numeric(8,2)
		[Column("prop LSOA worst 10% nat-d. Ed, Skill, Train"                                                                                                 )] public decimal? PropLsoaWorst10NatDEdSkillTrain                { get; set; } // numeric(8,2)
		[Column("Rank prop LSOAs worst 10% nat-d. Ed, Skill, Train"                                                                                           )] public decimal? RankPropLsoAsWorst10NatDEdSkillTrain           { get; set; } // numeric(8,2)
		[Column("Avg Rank-e. Health Dep and Disability"                                                                                                       )] public decimal? AvgRankEHealthDepAndDisability                 { get; set; } // numeric(8,2)
		[Column("Rank Avg score-e. Health Dep and Disability"                                                                                                 )] public decimal? RankAvgScoreEHealthDepAndDisability            { get; set; } // numeric(8,2)
		[Column("Avg Score-e. Health Dep and Disability"                                                                                                      )] public decimal? AvgScoreEHealthDepAndDisability                { get; set; } // numeric(8,2)
		[Column("Rank Avg rank-e. Health Dep and Disability"                                                                                                  )] public decimal? RankAvgRankEHealthDepAndDisability             { get; set; } // numeric(8,2)
		[Column("prop LSOA worst 10% nat-e. Health Dep and Disability"                                                                                        )] public decimal? PropLsoaWorst10NatEHealthDepAndDisability      { get; set; } // numeric(8,2)
		[Column("Rank prop LSOAs worst 10% nat-e. Health Dep and Disability"                                                                                  )] public decimal? RankPropLsoAsWorst10NatEHealthDepAndDisability { get; set; } // numeric(8,2)
		[Column("Avg Score-f. Crime"                                                                                                                          )] public decimal? AvgScoreFCrime                                 { get; set; } // numeric(8,2)
		[Column("Avg Rank-f. Crime"                                                                                                                           )] public decimal? AvgRankFCrime                                  { get; set; } // numeric(8,2)
		[Column("Rank prop LSOAs worst 10% nat-f. Crime"                                                                                                      )] public decimal? RankPropLsoAsWorst10NatFCrime                  { get; set; } // numeric(8,2)
		[Column("prop LSOA worst 10% nat-f. Crime"                                                                                                            )] public decimal? PropLsoaWorst10NatFCrime                       { get; set; } // numeric(8,2)
		[Column("Rank Avg score-f. Crime"                                                                                                                     )] public decimal? RankAvgScoreFCrime                             { get; set; } // numeric(8,2)
		[Column("Rank Avg rank-f. Crime"                                                                                                                      )] public decimal? RankAvgRankFCrime                              { get; set; } // numeric(8,2)
		[Column("Avg Rank-g. Bars to Housing and Services"                                                                                                    )] public decimal? AvgRankGBarsToHousingAndServices               { get; set; } // numeric(8,2)
		[Column("Rank Avg score-g. Bars to Housing and Services"                                                                                              )] public decimal? RankAvgScoreGBarsToHousingAndServices          { get; set; } // numeric(8,2)
		[Column("Rank prop LSOAs worst 10%. Bars to Housing and Services"                                                                                     )] public decimal? RankPropLsoAsWorst10BarsToHousingAndServices   { get; set; } // numeric(8,2)
		[Column("prop LSOA worst 10%. Bars to Housing and Services"                                                                                           )] public decimal? PropLsoaWorst10BarsToHousingAndServices        { get; set; } // numeric(8,2)
		[Column("Rank Avg rank-g. Bars to Housing and Services"                                                                                               )] public decimal? RankAvgRankGBarsToHousingAndServices           { get; set; } // numeric(8,2)
		[Column("Avg Score-g. Bars to Housing and Services"                                                                                                   )] public decimal? AvgScoreGBarsToHousingAndServices              { get; set; } // numeric(8,2)
		[Column("prop LSOA worst 10% nat-h. Liv-Env-dep"                                                                                                      )] public decimal? PropLsoaWorst10NatHLivEnvDep                   { get; set; } // numeric(8,2)
		[Column("Avg Score-h. Liv-Env-dep"                                                                                                                    )] public decimal? AvgScoreHLivEnvDep                             { get; set; } // numeric(8,2)
		[Column("Rank Avg score-h. Liv-Env-dep"                                                                                                               )] public decimal? RankAvgScoreHLivEnvDep                         { get; set; } // numeric(8,2)
		[Column("Rank prop LSOAs worst 10% nat-h. Liv-Env-dep"                                                                                                )] public decimal? RankPropLsoAsWorst10NatHLivEnvDep              { get; set; } // numeric(8,2)
		[Column("Avg Rank-h. Liv-Env-dep"                                                                                                                     )] public decimal? AvgRankHLivEnvDep                              { get; set; } // numeric(8,2)
		[Column("Rank Avg rank-h. Liv-Env-dep"                                                                                                                )] public decimal? RankAvgRankHLivEnvDep                          { get; set; } // numeric(8,2)
		[Column("Rank Avg rank-i. IDAO"                                                                                                                       )] public decimal? RankAvgRankIIdao                               { get; set; } // numeric(8,2)
		[Column("prop LSOA worst 10% nat-i. IDAO"                                                                                                             )] public decimal? PropLsoaWorst10NatIIdao                        { get; set; } // numeric(8,2)
		[Column("Rank prop LSOAs worst 10% nat-i. IDAO"                                                                                                       )] public decimal? RankPropLsoAsWorst10NatIIdao                   { get; set; } // numeric(8,2)
		[Column("Avg Rank-i. IDAO"                                                                                                                            )] public decimal? AvgRankIIdao                                   { get; set; } // numeric(8,2)
		[Column("Avg Score-i. IDAO"                                                                                                                           )] public decimal? AvgScoreIIdao                                  { get; set; } // numeric(8,2)
		[Column("Rank Avg score-i. IDAO"                                                                                                                      )] public decimal? RankAvgScoreIIdao                              { get; set; } // numeric(8,2)
		[Column("prop LSOA worst 10% nat-j. IDAOPI"                                                                                                           )] public decimal? PropLsoaWorst10NatJIdaopi                      { get; set; } // numeric(8,2)
		[Column("Avg Rank-j. IDAOPI"                                                                                                                          )] public decimal? AvgRankJIdaopi                                 { get; set; } // numeric(8,2)
		[Column("Avg Score-j. IDAOPI"                                                                                                                         )] public decimal? AvgScoreJIdaopi                                { get; set; } // numeric(8,2)
		[Column("Rank Avg rank-j. IDAOPI"                                                                                                                     )] public decimal? RankAvgRankJIdaopi                             { get; set; } // numeric(8,2)
		[Column("Rank prop LSOAs worst 10% nat-j. IDAOPI"                                                                                                     )] public decimal? RankPropLsoAsWorst10NatJIdaopi                 { get; set; } // numeric(8,2)
		[Column("Rank Avg score-j. IDAOPI"                                                                                                                    )] public decimal? RankAvgScoreJIdaopi                            { get; set; } // numeric(8,2)
		[Column("local_authority_id"                                                                                                                          )] public int?     LocalAuthorityId                               { get; set; } // integer

		#region Associations
		/// <summary>
		/// fk_local_authority_deprivation_indices_local_authority_id
		/// </summary>
		[Association(ThisKey = nameof(LocalAuthorityId), OtherKey = nameof(MeesSDK.LocalAuthority.Id))]
		public LocalAuthority? LocalAuthority { get; set; }
		#endregion
	}
}
