// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace MeesSDK
{
	[Table("main_heating_control_descriptions")]
	public class MainHeatingControlDescription
	{
		[Column("id"                  , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int     Id                  { get; set; } // integer
		[Column("name"                                                                                                  )] public string? Name                { get; set; } // character varying(256)
		[Column("trvs"                                                                                                  )] public bool?   Trvs                { get; set; } // boolean
		[Column("auto_charger"                                                                                          )] public bool?   AutoCharger         { get; set; } // boolean
		[Column("appliance_thermostat"                                                                                  )] public bool?   ApplianceThermostat { get; set; } // boolean
		[Column("community_controls"                                                                                    )] public bool?   CommunityControls   { get; set; } // boolean
		[Column("programmer"                                                                                            )] public bool?   Programmer          { get; set; } // boolean
		[Column("room_thermostat"                                                                                       )] public bool?   RoomThermostat      { get; set; } // boolean
		[Column("flat_rate"                                                                                             )] public bool?   FlatRate            { get; set; } // boolean
		[Column("flow_switch"                                                                                           )] public bool?   FlowSwitch          { get; set; } // boolean
	}
}
