// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace MeesSDK
{
	[Table("new_constituency_populations")]
	public class NewConstituencyPopulation
	{
		[Column("id"       , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int     Id        { get; set; } // integer
		[Column("code"                                                                                       )] public string? Code      { get; set; } // character varying(56)
		[Column("authority"                                                                                  )] public string? Authority { get; set; } // character varying(256)
		[Column("year"                                                                                       )] public short?  Year      { get; set; } // smallint
		[Column("total"                                                                                      )] public int?    Total     { get; set; } // integer
		[Column("men"                                                                                        )] public int?    Men       { get; set; } // integer
		[Column("women"                                                                                      )] public int?    Women     { get; set; } // integer
		[Column("f0"                                                                                         )] public int?    F0        { get; set; } // integer
		[Column("f1"                                                                                         )] public int?    F1        { get; set; } // integer
		[Column("f2"                                                                                         )] public int?    F2        { get; set; } // integer
		[Column("f3"                                                                                         )] public int?    F3        { get; set; } // integer
		[Column("f4"                                                                                         )] public int?    F4        { get; set; } // integer
		[Column("f5"                                                                                         )] public int?    F5        { get; set; } // integer
		[Column("f6"                                                                                         )] public int?    F6        { get; set; } // integer
		[Column("f7"                                                                                         )] public int?    F7        { get; set; } // integer
		[Column("f8"                                                                                         )] public int?    F8        { get; set; } // integer
		[Column("f9"                                                                                         )] public int?    F9        { get; set; } // integer
		[Column("f10"                                                                                        )] public int?    F10       { get; set; } // integer
		[Column("f11"                                                                                        )] public int?    F11       { get; set; } // integer
		[Column("f12"                                                                                        )] public int?    F12       { get; set; } // integer
		[Column("f13"                                                                                        )] public int?    F13       { get; set; } // integer
		[Column("f14"                                                                                        )] public int?    F14       { get; set; } // integer
		[Column("f15"                                                                                        )] public int?    F15       { get; set; } // integer
		[Column("f16"                                                                                        )] public int?    F16       { get; set; } // integer
		[Column("f17"                                                                                        )] public int?    F17       { get; set; } // integer
		[Column("f18"                                                                                        )] public int?    F18       { get; set; } // integer
		[Column("f19"                                                                                        )] public int?    F19       { get; set; } // integer
		[Column("f20"                                                                                        )] public int?    F20       { get; set; } // integer
		[Column("f21"                                                                                        )] public int?    F21       { get; set; } // integer
		[Column("f22"                                                                                        )] public int?    F22       { get; set; } // integer
		[Column("f23"                                                                                        )] public int?    F23       { get; set; } // integer
		[Column("f24"                                                                                        )] public int?    F24       { get; set; } // integer
		[Column("f25"                                                                                        )] public int?    F25       { get; set; } // integer
		[Column("f26"                                                                                        )] public int?    F26       { get; set; } // integer
		[Column("f27"                                                                                        )] public int?    F27       { get; set; } // integer
		[Column("f28"                                                                                        )] public int?    F28       { get; set; } // integer
		[Column("f29"                                                                                        )] public int?    F29       { get; set; } // integer
		[Column("f30"                                                                                        )] public int?    F30       { get; set; } // integer
		[Column("f31"                                                                                        )] public int?    F31       { get; set; } // integer
		[Column("f32"                                                                                        )] public int?    F32       { get; set; } // integer
		[Column("f33"                                                                                        )] public int?    F33       { get; set; } // integer
		[Column("f34"                                                                                        )] public int?    F34       { get; set; } // integer
		[Column("f35"                                                                                        )] public int?    F35       { get; set; } // integer
		[Column("f36"                                                                                        )] public int?    F36       { get; set; } // integer
		[Column("f37"                                                                                        )] public int?    F37       { get; set; } // integer
		[Column("f38"                                                                                        )] public int?    F38       { get; set; } // integer
		[Column("f39"                                                                                        )] public int?    F39       { get; set; } // integer
		[Column("f40"                                                                                        )] public int?    F40       { get; set; } // integer
		[Column("f41"                                                                                        )] public int?    F41       { get; set; } // integer
		[Column("f42"                                                                                        )] public int?    F42       { get; set; } // integer
		[Column("f43"                                                                                        )] public int?    F43       { get; set; } // integer
		[Column("f44"                                                                                        )] public int?    F44       { get; set; } // integer
		[Column("f45"                                                                                        )] public int?    F45       { get; set; } // integer
		[Column("f46"                                                                                        )] public int?    F46       { get; set; } // integer
		[Column("f47"                                                                                        )] public int?    F47       { get; set; } // integer
		[Column("f48"                                                                                        )] public int?    F48       { get; set; } // integer
		[Column("f49"                                                                                        )] public int?    F49       { get; set; } // integer
		[Column("f50"                                                                                        )] public int?    F50       { get; set; } // integer
		[Column("f51"                                                                                        )] public int?    F51       { get; set; } // integer
		[Column("f52"                                                                                        )] public int?    F52       { get; set; } // integer
		[Column("f53"                                                                                        )] public int?    F53       { get; set; } // integer
		[Column("f54"                                                                                        )] public int?    F54       { get; set; } // integer
		[Column("f55"                                                                                        )] public int?    F55       { get; set; } // integer
		[Column("f56"                                                                                        )] public int?    F56       { get; set; } // integer
		[Column("f57"                                                                                        )] public int?    F57       { get; set; } // integer
		[Column("f58"                                                                                        )] public int?    F58       { get; set; } // integer
		[Column("f59"                                                                                        )] public int?    F59       { get; set; } // integer
		[Column("f60"                                                                                        )] public int?    F60       { get; set; } // integer
		[Column("f61"                                                                                        )] public int?    F61       { get; set; } // integer
		[Column("f62"                                                                                        )] public int?    F62       { get; set; } // integer
		[Column("f63"                                                                                        )] public int?    F63       { get; set; } // integer
		[Column("f64"                                                                                        )] public int?    F64       { get; set; } // integer
		[Column("f65"                                                                                        )] public int?    F65       { get; set; } // integer
		[Column("f66"                                                                                        )] public int?    F66       { get; set; } // integer
		[Column("f67"                                                                                        )] public int?    F67       { get; set; } // integer
		[Column("f68"                                                                                        )] public int?    F68       { get; set; } // integer
		[Column("f69"                                                                                        )] public int?    F69       { get; set; } // integer
		[Column("f70"                                                                                        )] public int?    F70       { get; set; } // integer
		[Column("f71"                                                                                        )] public int?    F71       { get; set; } // integer
		[Column("f72"                                                                                        )] public int?    F72       { get; set; } // integer
		[Column("f73"                                                                                        )] public int?    F73       { get; set; } // integer
		[Column("f74"                                                                                        )] public int?    F74       { get; set; } // integer
		[Column("f75"                                                                                        )] public int?    F75       { get; set; } // integer
		[Column("f76"                                                                                        )] public int?    F76       { get; set; } // integer
		[Column("f77"                                                                                        )] public int?    F77       { get; set; } // integer
		[Column("f78"                                                                                        )] public int?    F78       { get; set; } // integer
		[Column("f79"                                                                                        )] public int?    F79       { get; set; } // integer
		[Column("f80"                                                                                        )] public int?    F80       { get; set; } // integer
		[Column("f81"                                                                                        )] public int?    F81       { get; set; } // integer
		[Column("f82"                                                                                        )] public int?    F82       { get; set; } // integer
		[Column("f83"                                                                                        )] public int?    F83       { get; set; } // integer
		[Column("f84"                                                                                        )] public int?    F84       { get; set; } // integer
		[Column("f85"                                                                                        )] public int?    F85       { get; set; } // integer
		[Column("f86"                                                                                        )] public int?    F86       { get; set; } // integer
		[Column("f87"                                                                                        )] public int?    F87       { get; set; } // integer
		[Column("f88"                                                                                        )] public int?    F88       { get; set; } // integer
		[Column("f89"                                                                                        )] public int?    F89       { get; set; } // integer
		[Column("f90"                                                                                        )] public int?    F90       { get; set; } // integer
		[Column("m0"                                                                                         )] public int?    M0        { get; set; } // integer
		[Column("m1"                                                                                         )] public int?    M1        { get; set; } // integer
		[Column("m2"                                                                                         )] public int?    M2        { get; set; } // integer
		[Column("m3"                                                                                         )] public int?    M3        { get; set; } // integer
		[Column("m4"                                                                                         )] public int?    M4        { get; set; } // integer
		[Column("m5"                                                                                         )] public int?    M5        { get; set; } // integer
		[Column("m6"                                                                                         )] public int?    M6        { get; set; } // integer
		[Column("m7"                                                                                         )] public int?    M7        { get; set; } // integer
		[Column("m8"                                                                                         )] public int?    M8        { get; set; } // integer
		[Column("m9"                                                                                         )] public int?    M9        { get; set; } // integer
		[Column("m10"                                                                                        )] public int?    M10       { get; set; } // integer
		[Column("m11"                                                                                        )] public int?    M11       { get; set; } // integer
		[Column("m12"                                                                                        )] public int?    M12       { get; set; } // integer
		[Column("m13"                                                                                        )] public int?    M13       { get; set; } // integer
		[Column("m14"                                                                                        )] public int?    M14       { get; set; } // integer
		[Column("m15"                                                                                        )] public int?    M15       { get; set; } // integer
		[Column("m16"                                                                                        )] public int?    M16       { get; set; } // integer
		[Column("m17"                                                                                        )] public int?    M17       { get; set; } // integer
		[Column("m18"                                                                                        )] public int?    M18       { get; set; } // integer
		[Column("m19"                                                                                        )] public int?    M19       { get; set; } // integer
		[Column("m20"                                                                                        )] public int?    M20       { get; set; } // integer
		[Column("m21"                                                                                        )] public int?    M21       { get; set; } // integer
		[Column("m22"                                                                                        )] public int?    M22       { get; set; } // integer
		[Column("m23"                                                                                        )] public int?    M23       { get; set; } // integer
		[Column("m24"                                                                                        )] public int?    M24       { get; set; } // integer
		[Column("m25"                                                                                        )] public int?    M25       { get; set; } // integer
		[Column("m26"                                                                                        )] public int?    M26       { get; set; } // integer
		[Column("m27"                                                                                        )] public int?    M27       { get; set; } // integer
		[Column("m28"                                                                                        )] public int?    M28       { get; set; } // integer
		[Column("m29"                                                                                        )] public int?    M29       { get; set; } // integer
		[Column("m30"                                                                                        )] public int?    M30       { get; set; } // integer
		[Column("m31"                                                                                        )] public int?    M31       { get; set; } // integer
		[Column("m32"                                                                                        )] public int?    M32       { get; set; } // integer
		[Column("m33"                                                                                        )] public int?    M33       { get; set; } // integer
		[Column("m34"                                                                                        )] public int?    M34       { get; set; } // integer
		[Column("m35"                                                                                        )] public int?    M35       { get; set; } // integer
		[Column("m36"                                                                                        )] public int?    M36       { get; set; } // integer
		[Column("m37"                                                                                        )] public int?    M37       { get; set; } // integer
		[Column("m38"                                                                                        )] public int?    M38       { get; set; } // integer
		[Column("m39"                                                                                        )] public int?    M39       { get; set; } // integer
		[Column("m40"                                                                                        )] public int?    M40       { get; set; } // integer
		[Column("m41"                                                                                        )] public int?    M41       { get; set; } // integer
		[Column("m42"                                                                                        )] public int?    M42       { get; set; } // integer
		[Column("m43"                                                                                        )] public int?    M43       { get; set; } // integer
		[Column("m44"                                                                                        )] public int?    M44       { get; set; } // integer
		[Column("m45"                                                                                        )] public int?    M45       { get; set; } // integer
		[Column("m46"                                                                                        )] public int?    M46       { get; set; } // integer
		[Column("m47"                                                                                        )] public int?    M47       { get; set; } // integer
		[Column("m48"                                                                                        )] public int?    M48       { get; set; } // integer
		[Column("m49"                                                                                        )] public int?    M49       { get; set; } // integer
		[Column("m50"                                                                                        )] public int?    M50       { get; set; } // integer
		[Column("m51"                                                                                        )] public int?    M51       { get; set; } // integer
		[Column("m52"                                                                                        )] public int?    M52       { get; set; } // integer
		[Column("m53"                                                                                        )] public int?    M53       { get; set; } // integer
		[Column("m54"                                                                                        )] public int?    M54       { get; set; } // integer
		[Column("m55"                                                                                        )] public int?    M55       { get; set; } // integer
		[Column("m56"                                                                                        )] public int?    M56       { get; set; } // integer
		[Column("m57"                                                                                        )] public int?    M57       { get; set; } // integer
		[Column("m58"                                                                                        )] public int?    M58       { get; set; } // integer
		[Column("m59"                                                                                        )] public int?    M59       { get; set; } // integer
		[Column("m60"                                                                                        )] public int?    M60       { get; set; } // integer
		[Column("m61"                                                                                        )] public int?    M61       { get; set; } // integer
		[Column("m62"                                                                                        )] public int?    M62       { get; set; } // integer
		[Column("m63"                                                                                        )] public int?    M63       { get; set; } // integer
		[Column("m64"                                                                                        )] public int?    M64       { get; set; } // integer
		[Column("m65"                                                                                        )] public int?    M65       { get; set; } // integer
		[Column("m66"                                                                                        )] public int?    M66       { get; set; } // integer
		[Column("m67"                                                                                        )] public int?    M67       { get; set; } // integer
		[Column("m68"                                                                                        )] public int?    M68       { get; set; } // integer
		[Column("m69"                                                                                        )] public int?    M69       { get; set; } // integer
		[Column("m70"                                                                                        )] public int?    M70       { get; set; } // integer
		[Column("m71"                                                                                        )] public int?    M71       { get; set; } // integer
		[Column("m72"                                                                                        )] public int?    M72       { get; set; } // integer
		[Column("m73"                                                                                        )] public int?    M73       { get; set; } // integer
		[Column("m74"                                                                                        )] public int?    M74       { get; set; } // integer
		[Column("m75"                                                                                        )] public int?    M75       { get; set; } // integer
		[Column("m76"                                                                                        )] public int?    M76       { get; set; } // integer
		[Column("m77"                                                                                        )] public int?    M77       { get; set; } // integer
		[Column("m78"                                                                                        )] public int?    M78       { get; set; } // integer
		[Column("m79"                                                                                        )] public int?    M79       { get; set; } // integer
		[Column("m80"                                                                                        )] public int?    M80       { get; set; } // integer
		[Column("m81"                                                                                        )] public int?    M81       { get; set; } // integer
		[Column("m82"                                                                                        )] public int?    M82       { get; set; } // integer
		[Column("m83"                                                                                        )] public int?    M83       { get; set; } // integer
		[Column("m84"                                                                                        )] public int?    M84       { get; set; } // integer
		[Column("m85"                                                                                        )] public int?    M85       { get; set; } // integer
		[Column("m86"                                                                                        )] public int?    M86       { get; set; } // integer
		[Column("m87"                                                                                        )] public int?    M87       { get; set; } // integer
		[Column("m88"                                                                                        )] public int?    M88       { get; set; } // integer
		[Column("m89"                                                                                        )] public int?    M89       { get; set; } // integer
		[Column("m90"                                                                                        )] public int?    M90       { get; set; } // integer
	}
}
