// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace MeesSDK
{
	[Table("nondomestic_buildings")]
	public class NondomesticBuilding
	{
		[Column("id"                       )] public int?     Id                      { get; set; } // integer
		[Column("building_reference_number")] public long?    BuildingReferenceNumber { get; set; } // bigint
		[Column("nondomestic"              )] public bool?    Nondomestic             { get; set; } // boolean
		[Column("address1"                 )] public string?  Address1                { get; set; } // character varying(256)
		[Column("address2"                 )] public string?  Address2                { get; set; } // character varying(256)
		[Column("address3"                 )] public string?  Address3                { get; set; } // character varying(256)
		[Column("postcode_id"              )] public int?     PostcodeId              { get; set; } // integer
		[Column("both_epc_types"           )] public bool?    BothEpcTypes            { get; set; } // boolean
		[Column("property_type_id"         )] public int?     PropertyTypeId          { get; set; } // integer
		[Column("built_form_id"            )] public int?     BuiltFormId             { get; set; } // integer
		[Column("area"                     )] public decimal? Area                    { get; set; } // numeric(9,4)
	}
}
