// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace MeesSDK
{
	[Table("ons_reference_sets")]
	public class OnsReferenceSet
	{
		[Column("id"                               , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int     Id                             { get; set; } // integer
		[Column("ons_id"                                                                                                             )] public int?    OnsId                          { get; set; } // integer
		[Column("theme"                                                                                                              )] public string? Theme                          { get; set; } // character varying(256)
		[Column("name"                                                                                                               )] public string? Name                           { get; set; } // character varying(512)
		[Column("url"                                                                                                                )] public string? Url                            { get; set; } // character varying(256)
		[Column("owner"                                                                                                              )] public string? Owner                          { get; set; } // character varying(256)
		[Column("coverage"                                                                                                           )] public string? Coverage                       { get; set; } // character varying(256)
		[Column("geo_unit"                                                                                                           )] public string? GeoUnit                        { get; set; } // character varying(256)
		[Column("population_coverage_or_definition"                                                                                  )] public string? PopulationCoverageOrDefinition { get; set; } // character varying(512)
		[Column("other_available"                                                                                                    )] public string? OtherAvailable                 { get; set; } // character varying(512)
		[Column("reference_period"                                                                                                   )] public string? ReferencePeriod                { get; set; } // character varying(256)
		[Column("update_cycle"                                                                                                       )] public string? UpdateCycle                    { get; set; } // character varying(256)
		[Column("first_date"                                                                                                         )] public string? FirstDate                      { get; set; } // character varying(256)
		[Column("latest_date"                                                                                                        )] public string? LatestDate                     { get; set; } // character varying(256)
		[Column("next_date"                                                                                                          )] public string? NextDate                       { get; set; } // character varying(256)
	}
}
