// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace MeesSDK
{
	[Table("postcodes_backup")]
	public class PostcodesBackup
	{
		[Column("id"                )] public int?     Id               { get; set; } // integer
		[Column("postcode"          )] public string?  Postcode         { get; set; } // character varying(32)
		[Column("local_authority_id")] public int?     LocalAuthorityId { get; set; } // integer
		[Column("constituency_id"   )] public int?     ConstituencyId   { get; set; } // integer
		[Column("lat"               )] public decimal? Lat              { get; set; } // numeric(10,3)
		[Column("lng"               )] public decimal? Lng              { get; set; } // numeric(10,3)
	}
}
