// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace MeesSDK
{
	[Table("property_types")]
	public class PropertyType
	{
		[Column("id"  , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int     Id   { get; set; } // integer
		[Column("name"                                                                                  )] public string? Name { get; set; } // character varying(24)

		#region Associations
		/// <summary>
		/// fk_buildings_property_type backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Building.PropertyTypeId))]
		public IEnumerable<Building> Buildings { get; set; } = null!;

		/// <summary>
		/// fk_property_type_id backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Depc.PropertyTypeId))]
		public IEnumerable<Depc> Depcs { get; set; } = null!;
		#endregion
	}
}
