// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace MeesSDK
{
	[Table("uprn_sources")]
	public class UprnSource
	{
		[Column("id"  , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int     Id   { get; set; } // integer
		[Column("name"                                                                                  )] public string? Name { get; set; } // character varying(128)

		#region Associations
		/// <summary>
		/// fk_uprn_source_id backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Epc.UprnSourceId))]
		public IEnumerable<Epc> Epcs { get; set; } = null!;
		#endregion
	}
}
